# Generated by Django 2.1 on 2019-05-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inftecnica', models.TextField(verbose_name='Informação Técnica')),
                ('infalergia', models.TextField(blank=True, null=True, verbose_name='Informação sobre alergênicos')),
                ('infnutricional', models.TextField(blank=True, null=True, verbose_name='Informação Nutricional')),
                ('escolha', models.TextField(blank=True, null=True, verbose_name='Por que escolher esse produto?')),
                ('marca', models.CharField(max_length=50, verbose_name='Sobre a Marca')),
                ('ingredientes', models.TextField(blank=True, null=True, verbose_name='Ingredientes')),
                ('recomendacao', models.TextField(blank=True, null=True, verbose_name='Recomendação de consumo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em ')),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em ')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em ')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Pendente'), (1, 'Aprovado'), (2, 'Cancelado')], default=1, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em ')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Detalhe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em ')),
            ],
            options={
                'verbose_name': 'Detalhe',
                'verbose_name_plural': 'Detalhes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição Simples')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='midia', verbose_name='Foto')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em ')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='detalhe',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='app.Produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='app.Produto', verbose_name='Produto'),
        ),
    ]
