# Generated by Django 2.1.7 on 2019-03-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('preco', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Preço')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição Simples')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('categoria', models.CharField(max_length=10, verbose_name='Categoria')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='midia', verbose_name='Foto')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em ')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
