# Generated by Django 2.1.7 on 2019-05-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190528_1101'),
    ]

    operations = [
    ]
