# Generated by Django 2.1.7 on 2019-05-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190529_0856'),
    ]

    operations = [
    ]
