# Generated by Django 2.1.7 on 2019-06-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190529_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterModelOptions(
            name='detalhe',
            options={'verbose_name': 'Detalhe', 'verbose_name_plural': 'Detalhes'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='update_at',
        ),
    ]
